# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba593b7f20c5f01ea5a6969155d9df7ef59faa9fb77e068d2bd0f29f6cb639999514202a81605809760304b0451a4ae5476ee178a8539a1fdf1be603c539449

test:
  secret_key_base: 970dce9d1796438a1dc76c8fe01b00b2a99964e558fdb19c318cfde7b104ad00390baa801119cc8c066343b6230757aaad1e9506e173917d2ab04dde8dda91cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
